spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kata_test
    username: root
    password: Grib_9096513234!
  web:
    resources:
      static-locations: classpath:/templates/, classpath:/resources/, classpath:/static/, classpath:/public/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    open-in-view: true
